# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  smartmedrestapi:
    image: stuckmariano/smartmedrestapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5286:5286  
  db:
    image: postgres:14.1
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
